# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180414_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, upload_to='files/news'),
        ),
    ]
