# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180416_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkstothesocialnetwork',
            name='email',
        ),
        migrations.AddField(
            model_name='linkstothesocialnetwork',
            name='mail',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='linkstothesocialnetwork',
            name='skype',
            field=models.CharField(default='', max_length=150),
        ),
    ]
