# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 07:58
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180416_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
