# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 05:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20180418_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesofaccordion',
            name='image',
        ),
        migrations.RemoveField(
            model_name='filesofaccordion',
            name='short_description_for_image',
        ),
        migrations.AddField(
            model_name='filesofaccordion',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
